# Generated by Django 5.0.1 on 2024-02-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ORDER_STATUS',
            new_name='order_status',
        ),
    ]
